version: '3.8'

services:
  # Next.js アプリケーション
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      # ソースコードをマウント（ホットリロード用）
      - .:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - .env.local
    command: npm run dev
    
  # ローカル開発用データベース（オプション）
  # 本番ではSupabaseを使用するため、テスト用途のみ
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: llmochecker_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    profiles:
      - local-db  # docker-compose --profile local-db up で起動

volumes:
  postgres_data: